#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

(require_once __DIR__.'/bootstrap/app.php')->handleRequest(Application::configure(basePath: __DIR__))->handleCommand(new Symfony\Component\Console\Input\ArgvInput, new Symfony\Component\Console\Output\ConsoleOutput);
